@url = http://localhost:2222/api/panaderia/image
@type = application/json

####
GET {{url}}
Content-Type: {{type}}

####
GET {{url}}/3
Content-Type: {{type}}

####
POST {{url}}
Content-Type: {{type}}

{
	"url" : "https://3.bp.blogspot.com/-9FCo8Mi50u8/T2tjN1GehZI/AAAAAAAAH5I/KU199g3zU48/s1600/enlustrados+(1).jpg",
	"breadBook" : { "id" : 2 }
}


####
PUT {{url}}/1
Content-Type: {{type}}

{
	"name" : "Caja de panes rosca ",
	"amount" : 11,
	"detail" : "Caja con 11 panes roca y sorpresa",
	"price" : 1.11
}
####
DELETE {{url}}/1
Content-Type: {{type}}