@url = http://localhost:2222/api/panaderia/user
@type = application/json

####
GET {{url}}
Content-Type: {{type}}

####
GET {{url}}/1
Content-Type: {{type}}

####
POST {{url}}
Content-Type: {{type}}
{
	"name" : "Andersonn Macias",
	"email" : "ander23k@gmail.com",
	"phone" : "095922465",
	"role" : "DELIVERY"
}

####
PUT {{url}}/1
Content-Type: {{type}}
{
	"name" : "Andersonn Macias",
	"email" : "ander23k@gmail.com",
	"phone" : "095922465",
	"role" : "DELIVERY"
}

####
DELETE {{url}}/1
Content-Type: {{type}}